# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dhcauchy <- function(x, location, sigma) {
    .Call('_cppbart_dhcauchy', PACKAGE = 'cppbart', x, location, sigma)
}

bart <- function(x, y, n_tree, n_mcmc, n_burn, n_min_size, tau, mu, tau_mu, naive_sigma, a_tau, d_tau, alpha, beta) {
    .Call('_cppbart_bart', PACKAGE = 'cppbart', x, y, n_tree, n_mcmc, n_burn, n_min_size, tau, mu, tau_mu, naive_sigma, a_tau, d_tau, alpha, beta)
}

