# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

seq_along <- function(n) {
    .Call('_cppbart_seq_along', PACKAGE = 'cppbart', n)
}

grow <- function(curr_tree, x) {
    .Call('_cppbart_grow', PACKAGE = 'cppbart', curr_tree, x)
}

